-- FarmFlow V1 — fresh install only
-- Generated from the live Supabase schema inventory.
-- DO NOT run this file against the existing working database.

create extension if not exists pgcrypto;

-- shipment_code is backed by a separate user-facing sequence.
create sequence if not exists public.shipment_code_seq start with 1 increment by 1;

create table public.users (
  id uuid not null,
  name text,
  email text,
  role text not null,
  farm_code text,
  active boolean default true not null,
  created_at timestamptz default now() not null,
  farm_name text default 'FarmFlow'::text not null
);

create table public.batches (
  batch_code text not null,
  purchase_date date not null,
  market_city text not null,
  supplier text,
  breed text,
  purchase_rate numeric not null,
  animal_count integer not null,
  total_weight numeric not null,
  already_tagged boolean default false not null,
  notes text,
  created_by uuid,
  created_at timestamptz default now() not null,
  id bigint generated by default as identity not null
);

create table public.shipments (
  id bigint generated by default as identity not null,
  shipment_code text default ('S'::text || lpad((nextval('shipment_code_seq'::regclass))::text, 3, '0'::text)) not null,
  shipment_date date not null,
  animal_count integer not null,
  meat_rate numeric not null,
  offal_rate numeric not null,
  daily_feed_cost numeric,
  created_by uuid,
  created_at timestamptz default now() not null
);

create table public.animals (
  tag text not null,
  purchase_weight numeric not null,
  induction_weight numeric,
  induction_date date,
  status text default 'purchased'::text not null,
  created_at timestamptz default now() not null,
  id bigint generated by default as identity not null,
  batch_id bigint not null,
  shipment_id bigint,
  out_weight numeric,
  meat_weight numeric,
  mortality_date date
);

create table public.farm_lookup_values (
  id uuid default gen_random_uuid() not null,
  category text not null,
  value text not null,
  active boolean default true not null,
  created_by uuid default auth.uid(),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table public.farm_tag_config (
  id smallint default 1 not null,
  tag_mode text not null,
  tag_prefix text,
  tag_separator text,
  tag_min_digits integer default 6 not null,
  configured_by uuid,
  configured_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table public.induction_corrections (
  id bigint generated always as identity not null,
  animal_id bigint not null,
  tag text not null,
  old_weight numeric not null,
  new_weight numeric not null,
  induction_date date,
  reason text not null,
  changed_by uuid not null,
  changed_at timestamptz default now() not null
);

create table public.purchase_corrections (
  id bigint generated always as identity not null,
  action text not null,
  animal_id bigint not null,
  batch_id bigint not null,
  batch_code text not null,
  old_values jsonb not null,
  new_values jsonb,
  reason text not null,
  changed_by uuid not null,
  changed_at timestamptz default now() not null
);
